# The groupName avoids naming conflicts on the Kubernetes API, it should be set by the
# author of the webhook a unique domain that the author owns. For
# example: some-provider-webhook.mycompany.tld , or
# some-provider-webhook.mypersonalsite.tld if your webhook is a personal open-source
# project.
# Once set to a unique domain name by the webhook author, it does not need to be further
# adjusted by the users of a webhook chart!
# The name will need to be referenced in each Issuer's `webhook` stanza to
# inform cert-manager of where to send ChallengePayload resources in order to
# solve the DNS01 challenge.
groupName: ipam.illinois.edu

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

image:
  repository: graduate.azurecr.io/illinois-infoblox-webhook
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
